version: 2

project_name: tasknova

builds:
  - id: linux_amd64
    binary: tasknova
    main: ./main.go
    goos: [linux]
    goarch: [amd64]
  - id: linux_arm64
    binary: tasknova
    main: ./main.go
    goos: [linux]
    goarch: [arm64]
  - id: darwin_amd64
    binary: tasknova
    main: ./main.go
    goos: [darwin]
    goarch: [amd64]
  - id: darwin_arm64
    binary: tasknova
    main: ./main.go
    goos: [darwin]
    goarch: [arm64]
  - id: windows_amd64
    binary: tasknova.exe
    main: ./main.go
    goos: [windows]
    goarch: [amd64]
  - id: windows_arm64
    binary: tasknova.exe
    main: ./main.go
    goos: [windows]
    goarch: [arm64]

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: tasknova
    repository:
      owner: joaaomanooel
      name: homebrew-tap  # Changed from 'tap' to 'homebrew-tap'
      token: "{{ .Env.GITHUB_TOKEN }}"  # Added token for authentication
    homepage: https://github.com/joaaomanooel/cli-tasknova
    description: "A CLI task manager for organizing tasks and notes"
    license: MIT
    install: |
      bin.install "tasknova"
    test: |
      system "#{bin}/tasknova --version"

scoops:
  - name: tasknova
    repository:
      owner: joaaomanooel
      name: bucket
    homepage: https://github.com/joaaomanooel/cli-tasknova
    description: "TaskNova CLI for managing tasks and notes"
    license: MIT
    url_template: "https://github.com/joaaomanooel/cli-tasknova/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    persist:
      - "data"

changelog:
  sort: asc

snapshot:
  version_template: "{{ .Tag }}-{{ .ShortCommit }}"
