version: 2

project_name: tasknova

builds:
  - binary: tasknova
    main: ./main.go
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
    files:
      - docs/man/*

# brews:
#   - name: tasknova
#     repository:
#       owner: joaaomanooel
#       name: tap
#     homepage: https://github.com/joaaomanooel/cli-tasknova
#     skip_upload: false

# brews:
#   - repository:
#       owner: joaaomanooel
#       name: tap
#       token: "{{ .Env.GITHUB_TOKEN }}"
#     goarm: "7"
#     homepage: https://github.com/joaaomanooel/cli-tasknova
#     license: MIT
#     description: "A CLI task manager"

brews:
  - name: tasknova
    repository:
      owner: joaaomanooel
      name: homebrew-tap  # Changed from 'tap' to 'homebrew-tap'
      token: "{{ .Env.GITHUB_TOKEN }}"  # Added token for authentication
    homepage: https://github.com/joaaomanooel/cli-tasknova
    description: "A CLI task manager for organizing tasks and notes"
    license: MIT
    install: |
      bin.install "tasknova"
    test: |
      system "#{bin}/tasknova --version"

    # extra_install: |-
    #   bash_completion.install "completions/tasknova.bash" => "tasknova"
    #   zsh_completion.install "completions/tasknova.zsh" => "_tasknova"
    #   fish_completion.install "completions/tasknova.fish"
    #   man1.install "docs/man/tasknova.1.gz"

changelog:
  sort: asc

snapshot:
  version_template: "{{ .Tag }}-{{ .ShortCommit }}"
