version: 2

project_name: tasknova

builds:
  - binary: tasknova
    main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
    files:
      - docs/man/*

brews:
  - name: joaaomanooel-tasknova
    repository:
      owner: joaaomanooel
      name: tap
    homepage: https://github.com/joaaomanooel/cli-tasknova
    skip_upload: false

scoops:
  - name: joaaomanooel-tasknova
    repository:
      owner: joaaomanooel
      name: bucket
    homepage: https://github.com/joaaomanooel/cli-tasknova
    description: "TaskNova CLI for managing tasks and notes"
    license: MIT
    url_template: "https://github.com/joaaomanooel/cli-tasknova/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    persist:
      - "data"

changelog:
  sort: asc

snapshot:
  version_template: "{{ .Tag }}-{{ .ShortCommit }}"
